[game]
desc             = """
Если ты стесняшка, заходи к нам 
Новый MRP сервер на классической сборке мейнтейнеров.
Баланс между "игрой в работку" и абсолютным хаосом. Стань первым в новом комьюнити!.

Загляни на нашу вики*

            (\__/)
            (•ㅅ•)      Помогаем
        ＿ノヽ ノ＼＿      новичкам
    `/　`/ ⌒Ｙ⌒ Ｙ  ヽ     освоиться в игре
    ( 　(三ヽ人　 /　  |     (\__/)
    |　ﾉ⌒＼ ￣￣ヽ   ノ     (•ㅅ•)
    ヽ＿＿＿＞､＿_／\\       /  \\>
"""
lobbyenabled     = true
lobbyduration = 180
soft_max_players = 60
panic_bunker.enabled = true
panic_bunker.disable_with_admins = true
panic_bunker.enable_without_admins = true
panic_bunker.show_reason = true
panic_bunker.min_overall_minutes = 60
panic_bunker.custom_reason = "В настоящий момент нет модераторов, а вы не наиграли достаточного количества минут (60) на нашем сервере."

[hub]
tags = "lang:ru,region:eu_e,rp:med"
advertise = true

[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 1
enabled = true

[net]
tickrate = 40
max_connections = 100

[infolinks]
discord = "https://discord.gg/sRSGDyGPw2"
wiki = "https://vanilla-station.ru/"
appeal = "https://discord.gg/NzAwkN9bH6"

[vote]
restart_required_ratio = 0.7

[netres]
limit = 10.0

[admin]
deadmin_on_join = true
new_player_threshold = 600
alert.min_players_sharing_connection = 2

[worldgen]
enabled = true

[auth]
mode = 1

[viewport]
maximum_width = 29

[server]
rules_file = "VanillaRulset"

[replay]
auto_record = true
