name: "Новая функциональность"
description: "Если вы хотите что-то добавить."
labels: ["triage"]
body:
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "Описание"
      description: "Опишите то что вы хотите добавить как можно подробнее."
  - type: textarea
    id: images
    validations:
      required: false
    attributes:
      label: "Изображения"
      description: "Пожалуйста, прикрепите изображения если это необходимо или может упростить работу."
